CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  student_name TEXT NOT NULL,
  class TEXT NOT NULL,
  parent_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  address TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS site_stats (
  id SERIAL PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value BIGINT DEFAULT 0
);

INSERT INTO site_stats (key, value) VALUES ('home_visits', 0) ON CONFLICT (key) DO NOTHING;
